# Generated by Django 5.0.2 on 2024-02-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_categorie_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='type',
            field=models.CharField(choices=[('Lg', 'Linge de Maison'), ('Bj', 'Bijoux'), ('Dc', 'Décor'), ('Al', 'Alimentaire'), ('Mb', 'Meuble'), ('Sn', 'Sanitaire'), ('Vt', 'Vêtement'), ('Vs', 'Vaisselle'), ('Jx', 'Jouets')], default='Alimentaire', max_length=2),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
