# Generated by Django 5.0.2 on 2024-02-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_produitnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitnc',
            name='duree_garantie',
            field=models.CharField(max_length=100),
        ),
    ]
